# Generated by Django 3.2.14 on 2022-07-18 23:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(choices=[('c', 'cortar cabelo'), ('l', 'lavar cabelo'), ('b', 'barbear')], max_length=15)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('horario', models.DurationField(verbose_name=datetime.timedelta(seconds=28800))),
                ('habilidade', models.ManyToManyField(related_name='serviços', to='app.Servico')),
            ],
        ),
        migrations.CreateModel(
            name='Antedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcionario')),
                ('servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serviços', to='app.funcionario')),
            ],
        ),
    ]
