# Generated by Django 3.2.14 on 2022-08-31 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serviço',
            new_name='Servico',
        ),
    ]
