# Generated by Django 3.2.14 on 2022-07-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='servico',
            field=models.CharField(choices=[('c', 'cortar cabelo'), ('l', 'lavar cabelo'), ('b', 'barbear'), ('n', 'corte navalha'), ('s', 'sobrancelha')], max_length=15),
        ),
    ]
