# Generated by Django 3.2.14 on 2022-07-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_servico_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='servico',
            field=models.CharField(choices=[('Corte de Cabelo', 'Corte de Cabelo'), ('Lavar Cabelo', 'Lavar Cabelo'), ('Barbear', 'Barbear'), ('Corte Navalhado', 'Corte Navalhado'), ('Sobrancelha', 'Sobrancelha')], max_length=15),
        ),
    ]
