# Generated by Django 3.2.14 on 2022-08-31 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220831_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 21, 3, 11, 298533, tzinfo=utc)),
        ),
    ]
