# Generated by Django 3.2.14 on 2022-07-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_servico_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='horario',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='servico',
            field=models.CharField(max_length=50),
        ),
    ]
