# Generated by Django 3.2.14 on 2022-08-31 21:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cliente_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 21, 6, 29, 168347, tzinfo=utc)),
        ),
    ]
