# Generated by Django 3.2.14 on 2022-07-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220725_1210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Antedimento',
            new_name='Atendimento',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='servico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serviços', to='app.servico'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='habilidade',
            field=models.ManyToManyField(to='app.Servico'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='horario',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
